import argparse
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, expr

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--listings_file", required=True)
    parser.add_argument("--bookings_file", required=True)
    parser.add_argument("--output_path", required=True)
    args = parser.parse_args()

    # Initialize Spark with ANSI disabled to prevent "stop-the-world" crashes
    spark = SparkSession.builder \
        .appName("ProductionListingsJoin") \
        .config("spark.sql.ansi.enabled", "false") \
        .getOrCreate()

    # 1. READ LISTINGS (The 194MB File)
    # We use PERMISSIVE mode to skip messy rows automatically
    listings = spark.read.csv(
        args.listings_file,
        header=True,
        quote='"',
        escape='"',
        multiLine=True,
        mode="PERMISSIVE"
    ).select(
        # Convert ID to number; if it's text like "Thanks to...", it becomes NULL
        expr("try_cast(id as bigint)").alias("listing_id"),
        col("name"),
        col("price")
    ).filter(col("listing_id").isNotNull()) # Drop the non-numeric "junk" rows

    # 2. READ BOOKINGS (The 42 random bookings generated by Airflow)
    bookings = spark.read.csv(
        args.bookings_file, 
        header=True, 
        inferSchema=True
    )

    # 3. JOIN & AGGREGATE
    # We join on listing_id and count how many bookings each listing got
    aggregated = listings.alias("L").join(
        bookings.alias("B"),
        col("L.listing_id") == col("B.listing_id"),
        how="inner"
    ).groupBy(
        col("L.listing_id"), 
        col("L.name"), 
        col("L.price")
    ).agg(
        count("B.booking_id").alias("booking_count")
    )

    # 4. WRITE THE RESULT
    aggregated.write.mode("overwrite") \
        .option("header", "true") \
        .csv(args.output_path)

    print(f"✅ Success! Results written to {args.output_path}")
    spark.stop()

if __name__ == "__main__":
    main()
